//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/c2f", ReplyAction="http://tempuri.org/IService1/c2fResponse")]
        int c2f(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/c2f", ReplyAction="http://tempuri.org/IService1/c2fResponse")]
        System.Threading.Tasks.Task<int> c2fAsync(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/f2c", ReplyAction="http://tempuri.org/IService1/f2cResponse")]
        int f2c(int fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/f2c", ReplyAction="http://tempuri.org/IService1/f2cResponse")]
        System.Threading.Tasks.Task<int> f2cAsync(int fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sort", ReplyAction="http://tempuri.org/IService1/sortResponse")]
        string sort(string commaSeparatedNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sort", ReplyAction="http://tempuri.org/IService1/sortResponse")]
        System.Threading.Tasks.Task<string> sortAsync(string commaSeparatedNumbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int c2f(int celsius) {
            return base.Channel.c2f(celsius);
        }
        
        public System.Threading.Tasks.Task<int> c2fAsync(int celsius) {
            return base.Channel.c2fAsync(celsius);
        }
        
        public int f2c(int fahrenheit) {
            return base.Channel.f2c(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<int> f2cAsync(int fahrenheit) {
            return base.Channel.f2cAsync(fahrenheit);
        }
        
        public string sort(string commaSeparatedNumbers) {
            return base.Channel.sort(commaSeparatedNumbers);
        }
        
        public System.Threading.Tasks.Task<string> sortAsync(string commaSeparatedNumbers) {
            return base.Channel.sortAsync(commaSeparatedNumbers);
        }
    }
}
